apiVersion: apps/v1
kind: Deployment
metadata:
  name: customercaregpt-worker
  labels:
    app: customercaregpt-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customercaregpt-worker
  template:
    metadata:
      labels:
        app: customercaregpt-worker
    spec:
      containers:
      - name: worker
        image: customercaregpt/backend:latest
        command: ["python", "-m", "rq", "worker", "--url", "redis://redis-service:6379"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: customercaregpt-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: customercaregpt-secrets
              key: redis-url
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: customercaregpt-secrets
              key: gemini-api-key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: customercaregpt-secrets
              key: secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: customercaregpt-worker-service
  labels:
    app: customercaregpt-worker
spec:
  selector:
    app: customercaregpt-worker
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: customercaregpt-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customercaregpt-worker
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
