# CustomerCareGPT Google Cloud Secret Manager Configuration
# This file contains the secret configurations for Google Cloud Run

# Secret definitions (these need to be created manually or via gcloud CLI)
# The actual secret values are stored in Google Secret Manager

# Backend Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: customercaregpt-secrets
type: Opaque
data:
  # These are base64 encoded values
  # To create: echo -n "your-secret-value" | base64
  gemini-api-key: <base64-encoded-gemini-api-key>
  secret-key: <base64-encoded-secret-key>
  stripe-api-key: <base64-encoded-stripe-api-key>
  stripe-webhook-secret: <base64-encoded-stripe-webhook-secret>
---
# Service Account for Cloud Run
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customercaregpt-sa
  annotations:
    iam.gke.io/gcp-service-account: customercaregpt-sa@YOUR_PROJECT_ID.iam.gserviceaccount.com
---
# IAM Policy Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: customercaregpt-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: customercaregpt-sa-role
subjects:
- kind: ServiceAccount
  name: customercaregpt-sa
  namespace: default
---
# Cluster Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customercaregpt-sa-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
