name: DISABLED - Frontend Integration and E2E Tests (Use backend-unit-tests.yml instead)

on:
  workflow_dispatch:

jobs:
  fe-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm run test:unit -- --run

      - name: Integration tests
        run: npm run test:integration

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: E2E tests (Playwright)
        run: npm run test:e2e


